# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Cloud, Code and Coffee"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Cloud Architect /.Net Core, Python, Azure, AWS, CQRS, Event Sourcing, Distributed Systems
github_username: ralphwillgoss
minimal_mistakes_skin: default
search: true
breadcrumbs: false
url: "https://ralphwillgoss.github.io"
repository: "ralphwillgoss/ralphwillgoss.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    block:
      line_numbers: false
github: [metadata] # Added this to avoid the "No GitHub API authentication could be found. Some fields may be missing or have incorrect data." warning when starting Jekyll.
feed:
  posts_limit: 200

# Outputting
permalink: /blog/:year/:month/:day/:title
paginate: 50
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-data

author:
  name   : "Ralph Willgoss"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Cloud, Code and Coffee<br/><br/>
            Cloud Architect /.Net Core, Python, Azure, AWS, CQRS, Event Sourcing, Distributed Systems"
  location: "London, UK"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ralphwillgoss"
    - label: "Company Website"
      icon: "fas fa-fw fa-link"
      url: "http://digitalsuperglue.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ralphwillgoss"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ralphwillgoss"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/743/ralph-willgoss"
    - label: "RSS"
      icon: "fas fa-fw fa-rss-square"
      url: "https://ralphwillgoss.github.io/feed.xml"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ralphwillgoss"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

# Removed until I set it up correctly
#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
#year_archive:
#  type: liquid
#  path: /year-archive/

analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : G-W7W0Q7JFQ0